[build]
incremental = true
rustflags = "-C target-cpu=native"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[alias]
cr_doc = "doc --no-deps"
