[package]
name = "tissue-pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tissue_pyo3"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
rand = "0.9"
rand_chacha = "0.9"
cellular_raza = { path="../../cellular_raza/", features = ["pyo3"]}
nalgebra = "0.34"
rayon = "1.9.0"
num = "0.4"
pyo3 = ">=0.24"
numpy = "0.27.1"
voronoice = "0.2.0"
approx.workspace = true
